# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотренно'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, upload_to='images/avatars/', verbose_name='Аватар'),
        ),
    ]
