# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0004_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-updated'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AddField(
            model_name='chat',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
