# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-27 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0011_svodnayavedomost'),
        ('taskmaster', '0005_auto_20180802_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='primary_docs.Station', verbose_name='Участок'),
        ),
    ]
