# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-20 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('primary_docs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='auto_accept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_accept_signs', to='primary_docs.Worker', verbose_name='Принял, механик'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='auto_passed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_pass_signs', to='primary_docs.Worker', verbose_name='Сдал, водитель'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='primary_docs.Car', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='car_took',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_took_signs', to='primary_docs.Worker', verbose_name='Автомобиль принял, водитель'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='check_out_allow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allow_mech_signs', to='primary_docs.Worker', verbose_name='Выезд разрешен, механик'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disp_signs', to='primary_docs.Worker', verbose_name='Диспетчер'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='primary_docs.Worker', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='primary_docs.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='primary_docs.Station', verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='tasks',
            field=models.ManyToManyField(related_name='waybills', to='primary_docs.DriverTask', verbose_name='Задание водителю'),
        ),
        migrations.AddField(
            model_name='station',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_stations', to='primary_docs.Worker', verbose_name='Начальник участка'),
        ),
        migrations.AddField(
            model_name='station',
            name='masters',
            field=models.ManyToManyField(blank=True, related_name='master_of_stations', to='primary_docs.Worker', verbose_name='Мастер участка'),
        ),
        migrations.AddField(
            model_name='station',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='primary_docs.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='outfittable',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_tables', to='primary_docs.Worker', verbose_name='Работник'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='accepted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_accept', to='primary_docs.Worker', verbose_name='К исполнению принял'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='brigadier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_brigadier', to='primary_docs.Worker', verbose_name='Бригадир'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='calculated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_calculate', to='primary_docs.Worker', verbose_name='Расчет составил'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='deposited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_deposited', to='primary_docs.Worker', verbose_name='Принял на ответственное хранение'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='primary_docs.OutfitEvent', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='expenses',
            field=models.ManyToManyField(related_name='outfit', to='primary_docs.OutfitExpense', verbose_name='Расходы материалов'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='issued',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_given', to='primary_docs.Worker', verbose_name='Наряд выдан'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='postings',
            field=models.ManyToManyField(blank=True, related_name='outfit', to='primary_docs.OutfitPosting', verbose_name='Оприходованная лесопродукция'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_responsible', to='primary_docs.Worker', verbose_name='Ответственный за ведение табеля'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='tables',
            field=models.ManyToManyField(related_name='outfit', to='primary_docs.OutfitTable', verbose_name='Табеля использования рабочего времени'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='work_accept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_work_accept', to='primary_docs.Worker', verbose_name='Работу принял'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='work_passed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_work_passed', to='primary_docs.Worker', verbose_name='Работу сдал'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='works',
            field=models.ManyToManyField(related_name='outfit', to='primary_docs.OutfitWork', verbose_name='Работы'),
        ),
        migrations.AddField(
            model_name='drivertask',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='primary_docs.Car', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='drivertask',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_tasks', to='primary_docs.Station', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='primary_docs.Fuel', verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='car',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='primary_docs.Station', verbose_name='Участок'),
        ),
    ]
