# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-21 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0002_auto_20180620_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 21, 11, 13, 47, 663491), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='outfitwork',
            name='done',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='outfitwork',
            name='done_norms',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Выполнено норм'),
        ),
        migrations.AlterField(
            model_name='outfitwork',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Нормы выработки'),
        ),
    ]
