# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primary_docs', '0003_auto_20180621_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfittable',
            name='deal_pricing',
        ),
        migrations.RemoveField(
            model_name='outfittable',
            name='festive',
        ),
        migrations.RemoveField(
            model_name='outfittable',
            name='sum_of_coefficients',
        ),
        migrations.AddField(
            model_name='outfit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Итого, сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outfit',
            name='amount_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Итого, премий'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='amount_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Итого, по коэффициенту'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='amount_conditions',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Итого, по условиям труда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outfit',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outfit',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, verbose_name='Премия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outfit',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, verbose_name='Коэффициент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outfittable',
            name='by_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, verbose_name='По коэффициенту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outfittable',
            name='by_conditions',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='По условиям труда'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outfit',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Всего, сумма'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='days_total',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Дней, всего'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='outfit', to='primary_docs.OutfitExpense', verbose_name='Расходы материалов'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='hours_total',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Часов, всего'),
        ),
        migrations.AlterField(
            model_name='outfittable',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Премия'),
        ),
        migrations.AlterField(
            model_name='outfittable',
            name='tariff_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тарифная ставка'),
        ),
    ]
