# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0005_auto_20180629_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='done_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Выработано норм, всего'),
        ),
    ]
