# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0006_auto_20180629_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfittable',
            name='done',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Выполнено норм'),
        ),
    ]
