# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primary_docs', '0008_auto_20180723_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='TractorRegForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('table_number', models.CharField(max_length=50, verbose_name='Табельный номер')),
                ('bonus', models.IntegerField(blank=True, verbose_name='Премия')),
                ('complexity', models.IntegerField(blank=True, verbose_name='Сложность')),
                ('classines', models.IntegerField(blank=True, verbose_name='Классность')),
                ('brigade', models.CharField(blank=True, max_length=50, verbose_name='Бригада')),
                ('trailer', models.CharField(blank=True, max_length=50, verbose_name='Прицепное устройство')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Отработано часов')),
                ('total_complete_nature', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выполнено: в натуре')),
                ('total_complete_norms', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выполнено: сменных норм')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: основная')),
                ('amount_bonus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: премия')),
                ('amount_complexity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: сложность')),
                ('amount_classines', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: классность')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: всего')),
                ('fuel_dep', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Горючее: остаток при получении учетного листа')),
                ('fuel_issued', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Горючее: заправлено')),
                ('fuel_ret', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Горючее: остаток при сдаче учетного листа')),
                ('total_fuel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Горючее: расход')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractor_regforms', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Учетный лист тракториста-машиниста',
                'verbose_name_plural': 'Учетные листы тракториста-машиниста',
            },
        ),
        migrations.CreateModel(
            name='TractorRegFormWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quarter', models.IntegerField(verbose_name='Квартал')),
                ('allotment', models.IntegerField(verbose_name='Выдел')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь, расстояние')),
                ('ref_name', models.CharField(max_length=50, verbose_name='Наименование справочника')),
                ('ref_page', models.CharField(max_length=50, verbose_name='Страница справочника')),
                ('units', models.CharField(choices=[('MC', 'M³'), ('MS', 'M²'), ('P', 'Шт'), ('HE', 'Га'), ('L', 'Л')], max_length=50, verbose_name='Еденицы измерения')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Отработано часов')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Норма выработки')),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расценка')),
                ('complete_nature', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выполнено, в натуре')),
                ('complete_norms', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выполнено сменных норм')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: основная')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: премия')),
                ('complexity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: сложность')),
                ('classines', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: классность')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: всего')),
                ('fuel_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расход горючего на еденицу работы')),
                ('fuel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расход горючего всего')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractor_regforms_work', to='primary_docs.OutfitEvent', verbose_name='Наименование работы')),
            ],
            options={
                'verbose_name': 'Работа тракториста-машиниста',
                'verbose_name_plural': 'Работы тракториста-машиниста',
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Разряд'),
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='brigadier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tractor_regforms_brigadier', to='primary_docs.Worker', verbose_name='Бригадир'),
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tractor_regforms', to='primary_docs.Car', verbose_name='Трактор'),
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tractor_regforms_driver', to='primary_docs.Worker', verbose_name='Тракторист'),
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tractor_regforms', to='primary_docs.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tractor_regforms', to='primary_docs.Station', verbose_name='Отделение (участок)'),
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='trailerman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tractor_regforms_trailerman', to='primary_docs.Worker', verbose_name='Прицепщик'),
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='works',
            field=models.ManyToManyField(related_name='tractor_regform', to='primary_docs.TractorRegFormWork', verbose_name='Работы'),
        ),
    ]
