# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0009_auto_20180813_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kind',
            field=models.CharField(choices=[('L', 'Легковой'), ('H', 'Грузовой'), ('T', 'Трактор')], max_length=50, null=True, verbose_name='Тип автомобиля'),
        ),
        migrations.AlterField(
            model_name='outfitexpense',
            name='units',
            field=models.CharField(choices=[('MC', 'M³'), ('MS', 'M²'), ('P', 'Шт'), ('HE', 'Га'), ('L', 'Л'), ('KM', 'Км')], max_length=50, verbose_name='Еденицы измерения'),
        ),
        migrations.AlterField(
            model_name='outfitposting',
            name='units',
            field=models.CharField(choices=[('MC', 'M³'), ('MS', 'M²'), ('P', 'Шт'), ('HE', 'Га'), ('L', 'Л'), ('KM', 'Км')], max_length=50, verbose_name='Еденицы измерения'),
        ),
        migrations.AlterField(
            model_name='outfitwork',
            name='units',
            field=models.CharField(choices=[('MC', 'M³'), ('MS', 'M²'), ('P', 'Шт'), ('HE', 'Га'), ('L', 'Л'), ('KM', 'Км')], max_length=50, verbose_name='Еденицы измерения'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='amount_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: премия'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='amount_classines',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: классность'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='amount_complexity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: сложность'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Премия'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='brigade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Бригада'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='classines',
            field=models.IntegerField(blank=True, null=True, verbose_name='Классность'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='complexity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='fuel_issued',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Горючее: заправлено'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='table_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='trailer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Прицепное устройство'),
        ),
        migrations.AlterField(
            model_name='tractorregformwork',
            name='units',
            field=models.CharField(choices=[('MC', 'M³'), ('MS', 'M²'), ('P', 'Шт'), ('HE', 'Га'), ('L', 'Л'), ('KM', 'Км')], max_length=50, verbose_name='Еденицы измерения'),
        ),
    ]
