# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-27 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primary_docs', '0010_auto_20180820_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvodnayaVedomost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('prep_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата составления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svodnaya_vedomost', to=settings.AUTH_USER_MODEL, verbose_name='Составитель')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='svodnaya_vedomost', to='primary_docs.OutfitEvent', verbose_name='Вид работ')),
            ],
        ),
    ]
