# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0012_auto_20180827_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvodnayaZapis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Премия')),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Коэффициент')),
                ('classines', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Классность')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: основная')),
                ('amount_classines', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: классность')),
                ('recast_half', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: переработка в 1,5 раз')),
                ('recast_double', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: переработка в 2 раза')),
                ('amount_holydays', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: празднечные')),
                ('amount_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: премия')),
                ('amount_coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: коэффициент')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: всего')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svodnaya', to='primary_docs.Waybill', verbose_name='Путевой лист')),
            ],
            options={
                'verbose_name': 'Сводный расчет',
                'verbose_name_plural': 'Сводные расчеты',
            },
        ),
        migrations.AlterModelOptions(
            name='svodnayavedomost',
            options={'verbose_name': 'Сводная ведомость', 'verbose_name_plural': 'Сводные ведомости'},
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Оплата: основная'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата: всего'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: премия'),
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='classines',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: классность'),
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: коэффициент'),
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='holydays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: выходные'),
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Часы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='recast_double',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: переработка в 2 раза'),
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='recast_half',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: переработка в 1,5 раз'),
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='svodnaya_vedomost', to='primary_docs.Station', verbose_name='Производственный участок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='calcs',
            field=models.ManyToManyField(related_name='svodnaya_vedomost', to='primary_docs.SvodnayaZapis', verbose_name='Сводные расчеты'),
        ),
    ]
