# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0013_auto_20180827_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='conducted',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='departament',
            field=models.CharField(choices=[('les', 'Лес'), ('ceh', 'Цех'), ('pxs', 'ПХС'), ('mtm', 'МТМ')], max_length=50, null=True, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='conducted',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
        migrations.AddField(
            model_name='svodnayavedomost',
            name='departament',
            field=models.CharField(choices=[('les', 'Лес'), ('ceh', 'Цех'), ('pxs', 'ПХС'), ('mtm', 'МТМ')], max_length=50, null=True, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='conducted',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='departament',
            field=models.CharField(choices=[('les', 'Лес'), ('ceh', 'Цех'), ('pxs', 'ПХС'), ('mtm', 'МТМ')], max_length=50, null=True, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='conducted',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='departament',
            field=models.CharField(choices=[('les', 'Лес'), ('ceh', 'Цех'), ('pxs', 'ПХС'), ('mtm', 'МТМ')], max_length=50, null=True, verbose_name='Отдел'),
        ),
    ]
