# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0014_auto_20180831_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='departament',
            field=models.CharField(choices=[('les', 'Лес'), ('ceh', 'Цех'), ('phs', 'ПХС'), ('mtm', 'МТМ')], max_length=50, null=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='svodnayavedomost',
            name='departament',
            field=models.CharField(choices=[('les', 'Лес'), ('ceh', 'Цех'), ('phs', 'ПХС'), ('mtm', 'МТМ')], max_length=50, null=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='svodnayavedomost',
            name='prep_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата сосвтавления'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='departament',
            field=models.CharField(choices=[('les', 'Лес'), ('ceh', 'Цех'), ('phs', 'ПХС'), ('mtm', 'МТМ')], max_length=50, null=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='departament',
            field=models.CharField(choices=[('les', 'Лес'), ('ceh', 'Цех'), ('phs', 'ПХС'), ('mtm', 'МТМ')], max_length=50, null=True, verbose_name='Отдел'),
        ),
    ]
