# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0016_auto_20180903_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='svodnayavedomost',
            old_name='prep_date',
            new_name='created_date',
        ),
    ]
