# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0017_auto_20180903_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svodnayavedomost',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата составления'),
        ),
    ]
