# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0018_auto_20180903_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='place',
        ),
        migrations.AddField(
            model_name='outfit',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='primary_docs.Station', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='amount_conditions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итого, по условиям труда'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='conditions',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Условия труда'),
        ),
    ]
