# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0019_auto_20180904_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='svodnayavedomost',
            name='complexity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: сложность'),
        ),
        migrations.AlterField(
            model_name='svodnayavedomost',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: основная'),
        ),
    ]
