# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primary_docs', '0020_auto_20180907_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='NakopitelnayaVedomost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(choices=[('les', 'Лес'), ('ceh', 'Цех'), ('phs', 'ПХС'), ('mtm', 'МТМ')], max_length=50, null=True, verbose_name='Отдел')),
                ('conducted', models.BooleanField(default=False, verbose_name='Проведен')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата составления')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: основная')),
                ('complexity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: сложность')),
                ('classines', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: классность')),
                ('recast_half', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: переработка в 1,5 раз')),
                ('recast_double', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: переработка в 2 раза')),
                ('holydays', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: выходные')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: премия')),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплата: коэффициент')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата: всего')),
                ('man_days', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Человеко-дней(машино-смен)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nakopitelnaya_vedomost', to=settings.AUTH_USER_MODEL, verbose_name='Составитель')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nakopitelnaya_vedomost', to='primary_docs.OutfitEvent', verbose_name='Вид работ')),
                ('outfits', models.ManyToManyField(blank=True, related_name='vedomost', to='primary_docs.Outfit', verbose_name='Наряд-Акты')),
                ('regforms', models.ManyToManyField(blank=True, related_name='vedomost', to='primary_docs.TractorRegForm', verbose_name='Учетные листы тракториста-машиниста')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nakopitelnaya_vedomost', to='primary_docs.Station', verbose_name='Производственный участок')),
            ],
            options={
                'verbose_name': 'Накопительная ведомость',
                'verbose_name_plural': 'Накопительные ведомости',
                'default_related_name': 'nakopitelnaya_vedomost',
            },
        ),
    ]
