# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-18 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0021_nakopitelnayavedomost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['surname'], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regforms', to='primary_docs.OutfitEvent', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='car',
            name='kind',
            field=models.CharField(choices=[('L', 'Легковой'), ('H', 'Грузовой'), ('T', 'Трактор'), ('A', 'Автобус')], max_length=50, null=True, verbose_name='Тип автомобиля'),
        ),
        migrations.AlterField(
            model_name='tractorregformwork',
            name='event',
            field=models.TextField(max_length=500, null=True, verbose_name='Наименование'),
        ),
    ]
