# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0022_auto_20180918_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorregformwork',
            name='event',
            field=models.CharField(max_length=500, null=True, verbose_name='Наименование'),
        ),
    ]
