# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0024_auto_20180921_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfittable',
            name='importance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ответственные работы'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='amount_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Итого по премиям'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='amount_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Итого по коэффициенту'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='amount_importance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Итого, по ответственным работам'),
        ),
    ]
