# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0025_auto_20180924_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='amount_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итого по премиям'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='amount_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итого по коэффициенту'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='amount_importance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итого, по ответственным работам'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Премия'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Коэффициент'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='conditions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Условия труда'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='importance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ответственные работы'),
        ),
    ]
