# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primary_docs', '0026_auto_20180924_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Период')),
                ('created_date', models.DateTimeField(verbose_name='Дата создания')),
                ('departament', models.CharField(choices=[('les', 'Лес'), ('ceh', 'Цех'), ('phs', 'ПХС'), ('mtm', 'МТМ')], max_length=50, null=True, verbose_name='Отдел')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktime_tables', to=settings.AUTH_USER_MODEL, verbose_name='Составитель')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime_tables', to='primary_docs.Organization', verbose_name='Организация')),
                ('outfits', models.ManyToManyField(related_name='worktime_table', to='primary_docs.Outfit', verbose_name='Наряд-Акты')),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime_tables_performer', to='primary_docs.Worker', verbose_name='Исполнитель')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime_tables_responsible', to='primary_docs.Worker', verbose_name='Ответственный')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime_tables', to='primary_docs.Station', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Табель учета рабочего времени',
                'verbose_name_plural': 'Табеля учета рабочего времени',
            },
        ),
    ]
