# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-02 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0027_worktimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdays', jsonfield.fields.JSONField(default={}, verbose_name='Рабочие Дни')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktime_entries', to='primary_docs.Worker', verbose_name='Записи учета времени')),
            ],
            options={
                'verbose_name': 'Запись табеля учета рабочего времени',
                'verbose_name_plural': 'Записи табеля учета рабочего времени',
            },
        ),
        migrations.AddField(
            model_name='worktimetable',
            name='regforms',
            field=models.ManyToManyField(blank=True, related_name='worktime_table', to='primary_docs.TractorRegForm', verbose_name='Учетные листы тракториста-машиниста'),
        ),
        migrations.AddField(
            model_name='worktimetable',
            name='waybills',
            field=models.ManyToManyField(blank=True, related_name='worktime_table', to='primary_docs.Waybill', verbose_name='Путевые листы'),
        ),
        migrations.AlterField(
            model_name='worktimetable',
            name='outfits',
            field=models.ManyToManyField(blank=True, related_name='worktime_table', to='primary_docs.Outfit', verbose_name='Наряд-Акты'),
        ),
        migrations.AddField(
            model_name='worktimetable',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='worktime_table', to='primary_docs.WorkTimeEntry', verbose_name='Записи'),
        ),
    ]
