# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0028_auto_20181002_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimetable',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Всего часов'),
        ),
        migrations.AlterField(
            model_name='worktimetable',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='worktimetable',
            name='organization',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime_tables', to='primary_docs.Organization', verbose_name='Организация'),
        ),
    ]
