# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0029_auto_20181004_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('units', models.CharField(choices=[('MC', 'M³'), ('MS', 'M²'), ('P', 'Шт'), ('HE', 'Га'), ('L', 'Л'), ('KM', 'Км'), ('KG', 'Кг')], max_length=50, verbose_name='Еденицы измерения')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория материалов',
                'verbose_name_plural': 'Категории материалов',
            },
        ),
        migrations.AlterField(
            model_name='outfitexpense',
            name='units',
            field=models.CharField(choices=[('MC', 'M³'), ('MS', 'M²'), ('P', 'Шт'), ('HE', 'Га'), ('L', 'Л'), ('KM', 'Км'), ('KG', 'Кг')], max_length=50, verbose_name='Еденицы измерения'),
        ),
        migrations.AlterField(
            model_name='outfitposting',
            name='units',
            field=models.CharField(choices=[('MC', 'M³'), ('MS', 'M²'), ('P', 'Шт'), ('HE', 'Га'), ('L', 'Л'), ('KM', 'Км'), ('KG', 'Кг')], max_length=50, verbose_name='Еденицы измерения'),
        ),
        migrations.AlterField(
            model_name='outfitwork',
            name='units',
            field=models.CharField(choices=[('MC', 'M³'), ('MS', 'M²'), ('P', 'Шт'), ('HE', 'Га'), ('L', 'Л'), ('KM', 'Км'), ('KG', 'Кг')], max_length=50, verbose_name='Еденицы измерения'),
        ),
        migrations.AlterField(
            model_name='tractorregformwork',
            name='units',
            field=models.CharField(choices=[('MC', 'M³'), ('MS', 'M²'), ('P', 'Шт'), ('HE', 'Га'), ('L', 'Л'), ('KM', 'Км'), ('KG', 'Кг')], max_length=50, verbose_name='Еденицы измерения'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='primary_docs.MaterialCategory', verbose_name='Категория'),
        ),
    ]
