# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0030_auto_20181025_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfitexpense',
            name='name',
        ),
        migrations.RemoveField(
            model_name='outfitexpense',
            name='units',
        ),
        migrations.RemoveField(
            model_name='outfitposting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='outfitposting',
            name='units',
        ),
        migrations.AddField(
            model_name='outfitexpense',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='primary_docs.Material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='outfitposting',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='primary_docs.Material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='outfitexpense',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Стоимость, руб.'),
        ),
    ]
