# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0031_auto_20181025_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='primary_docs.Fuel', verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Остаток бензина'),
        ),
        migrations.AlterField(
            model_name='car',
            name='kind',
            field=models.CharField(choices=[('L', 'Легковой'), ('H', 'Грузовой'), ('T', 'Трактор'), ('C', 'Цистерна'), ('S', 'Шасси'), ('P', 'Прицеп')], max_length=50, null=True, verbose_name='Тип автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Показания спидометра'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Государственный номерной знак'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rate_hard_s',
            field=models.FloatField(default=0, verbose_name='Расход топлива лето, тяж. усл'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rate_hard_w',
            field=models.FloatField(default=0, verbose_name='Расход топлива, зима тяж. усл'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rate_normal_s',
            field=models.FloatField(default=0, verbose_name='Расход топлива, лето, норм. усл'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rate_normal_w',
            field=models.FloatField(default=0, verbose_name='Расход топлива, зима, норм. усл'),
        ),
    ]
