# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-18 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primary_docs', '0032_auto_20181107_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestArrivalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forest_arrival_reports', to=settings.AUTH_USER_MODEL, verbose_name='Составитель')),
                ('outfits', models.ManyToManyField(blank=True, related_name='forest_arrival_reports', to='primary_docs.Outfit', verbose_name='Наряд-Акты')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forest_arrival_reports', to='primary_docs.Station', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Акт прихода лесопродукции',
                'verbose_name_plural': 'Акты прихода лесопродукции',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-kind'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='outfitexpense',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость, руб.'),
        ),
    ]
