# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-19 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0033_auto_20181218_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='postings',
        ),
        migrations.AddField(
            model_name='outfitexpense',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='primary_docs.Outfit', verbose_name='Наряд-акт'),
        ),
        migrations.AddField(
            model_name='outfitposting',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='primary_docs.Outfit', verbose_name='Наряд-акт'),
        ),
    ]
