# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-20 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0034_auto_20181219_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forestarrivalreport',
            name='outfits',
        ),
        migrations.AddField(
            model_name='forestarrivalreport',
            name='postings',
            field=models.ManyToManyField(blank=True, related_name='forest_arrival_reports', to='primary_docs.OutfitPosting', verbose_name='Приход лесопродукции'),
        ),
    ]
