# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-21 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0036_auto_20181221_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recyclinglist',
            options={'verbose_name': 'Ведомость переработки', 'verbose_name_plural': 'Ведомости переработки'},
        ),
        migrations.AlterField(
            model_name='outfit',
            name='recycling_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='primary_docs.RecyclingList', verbose_name='Ведомость переработки'),
        ),
    ]
