# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0037_auto_20181221_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitexpense',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='primary_docs.Outfit', verbose_name='Наряд-акт'),
        ),
        migrations.AlterField(
            model_name='outfitposting',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='primary_docs.Outfit', verbose_name='Наряд-акт'),
        ),
    ]
