# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-24 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0038_auto_20181224_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='works',
        ),
        migrations.AddField(
            model_name='outfittable',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='primary_docs.Outfit', verbose_name='Наряд-акт'),
        ),
        migrations.AddField(
            model_name='outfitwork',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='primary_docs.Outfit', verbose_name='Наряд-акт'),
        ),
    ]
