# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-26 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primary_docs', '0039_auto_20181224_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to=settings.AUTH_USER_MODEL, verbose_name='Составитель')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='primary_docs.Car', verbose_name='Автомобиль')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='primary_docs.Station', verbose_name='Участок')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='primary_docs.Worker', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Раздаточная ведомость',
                'verbose_name_plural': 'Раздаточные ведомости',
            },
        ),
        migrations.AddField(
            model_name='forestarrivalreport',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='recyclinglist',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='handout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='primary_docs.Handout', verbose_name='Раздаточная ведомость'),
        ),
    ]
