# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-27 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0040_auto_20181226_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='primary_docs.Fuel', verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='car',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='primary_docs.Station', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='drivertask',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='primary_docs.Car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='drivertask',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_tasks', to='primary_docs.Station', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='forestarrivalreport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forest_arrival_reports', to=settings.AUTH_USER_MODEL, verbose_name='Составитель'),
        ),
        migrations.AlterField(
            model_name='forestarrivalreport',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forest_arrival_reports', to='primary_docs.Station', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handouts', to=settings.AUTH_USER_MODEL, verbose_name='Составитель'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handouts', to='primary_docs.Car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handouts', to='primary_docs.Station', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handouts', to='primary_docs.Worker', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='primary_docs.MaterialCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='nakopitelnayavedomost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nakopitelnaya_vedomost', to=settings.AUTH_USER_MODEL, verbose_name='Составитель'),
        ),
        migrations.AlterField(
            model_name='nakopitelnayavedomost',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nakopitelnaya_vedomost', to='primary_docs.OutfitEvent', verbose_name='Вид работ'),
        ),
        migrations.AlterField(
            model_name='nakopitelnayavedomost',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nakopitelnaya_vedomost', to='primary_docs.Station', verbose_name='Производственный участок'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='accepted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfit_accept', to='primary_docs.Worker', verbose_name='К исполнению принял'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='brigadier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_brigadier', to='primary_docs.Worker', verbose_name='Бригадир'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='calculated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfit_calculate', to='primary_docs.Worker', verbose_name='Расчет составил'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='deposited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfit_deposited', to='primary_docs.Worker', verbose_name='Принял на ответственное хранение'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfits', to='primary_docs.OutfitEvent', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='issued',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfit_given', to='primary_docs.Worker', verbose_name='Наряд выдан'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='recycling_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits', to='primary_docs.RecyclingList', verbose_name='Ведомость переработки'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfit_responsible', to='primary_docs.Worker', verbose_name='Ответственный за ведение табеля'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfits', to='primary_docs.Station', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='work_accept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_work_accept', to='primary_docs.Worker', verbose_name='Работу принял'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='work_passed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfit_work_passed', to='primary_docs.Worker', verbose_name='Работу сдал'),
        ),
        migrations.AlterField(
            model_name='outfitexpense',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='primary_docs.Material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='outfitexpense',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='primary_docs.Outfit', verbose_name='Наряд-акт'),
        ),
        migrations.AlterField(
            model_name='outfitposting',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='primary_docs.Material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='outfitposting',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='primary_docs.Outfit', verbose_name='Наряд-акт'),
        ),
        migrations.AlterField(
            model_name='outfittable',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfit_tables', to='primary_docs.Worker', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='recyclinglist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_lists', to=settings.AUTH_USER_MODEL, verbose_name='Составитель'),
        ),
        migrations.AlterField(
            model_name='recyclinglist',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recycling_lists', to='primary_docs.Station', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='station',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='primary_docs.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='svodnayavedomost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='svodnaya_vedomost', to=settings.AUTH_USER_MODEL, verbose_name='Составитель'),
        ),
        migrations.AlterField(
            model_name='svodnayavedomost',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='svodnaya_vedomost', to='primary_docs.OutfitEvent', verbose_name='Вид работ'),
        ),
        migrations.AlterField(
            model_name='svodnayavedomost',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='svodnaya_vedomost', to='primary_docs.Station', verbose_name='Производственный участок'),
        ),
        migrations.AlterField(
            model_name='svodnayazapis',
            name='waybill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='svodnaya', to='primary_docs.Waybill', verbose_name='Путевой лист'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tractor_regforms', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='brigadier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tractor_regforms_brigadier', to='primary_docs.Worker', verbose_name='Бригадир'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tractor_regforms', to='primary_docs.Car', verbose_name='Трактор'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tractor_regforms_driver', to='primary_docs.Worker', verbose_name='Тракторист'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regforms', to='primary_docs.OutfitEvent', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tractor_regforms', to='primary_docs.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tractor_regforms', to='primary_docs.Station', verbose_name='Отделение (участок)'),
        ),
        migrations.AlterField(
            model_name='tractorregform',
            name='trailerman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tractor_regforms_trailerman', to='primary_docs.Worker', verbose_name='Прицепщик'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='auto_accept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auto_accept_signs', to='primary_docs.Worker', verbose_name='Принял, механик'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='auto_passed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auto_pass_signs', to='primary_docs.Worker', verbose_name='Сдал, водитель'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='primary_docs.Car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='car_took',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_took_signs', to='primary_docs.Worker', verbose_name='Автомобиль принял, водитель'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='check_out_allow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allow_mech_signs', to='primary_docs.Worker', verbose_name='Выезд разрешен, механик'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disp_signs', to='primary_docs.Worker', verbose_name='Диспетчер'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='primary_docs.Worker', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='handout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='primary_docs.Handout', verbose_name='Раздаточная ведомость'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='primary_docs.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='primary_docs.Station', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='primary_docs.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='primary_docs.Station', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='worktimeentry',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worktime_entries', to='primary_docs.Worker', verbose_name='Записи учета времени'),
        ),
        migrations.AlterField(
            model_name='worktimetable',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worktime_tables', to=settings.AUTH_USER_MODEL, verbose_name='Составитель'),
        ),
        migrations.AlterField(
            model_name='worktimetable',
            name='organization',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worktime_tables', to='primary_docs.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='worktimetable',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worktime_tables_performer', to='primary_docs.Worker', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='worktimetable',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worktime_tables_responsible', to='primary_docs.Worker', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='worktimetable',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worktime_tables', to='primary_docs.Station', verbose_name='Участок'),
        ),
    ]
