# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-09 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primary_docs', '0041_auto_20181227_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fuel', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Всего ГСМ')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('kind', models.CharField(choices=[('OF', 'Наряд-акт'), ('WB', 'Путевой лист'), ('TR', 'Учетный лист тракториста')], max_length=50, null=True, verbose_name='Тип документа')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Составитель')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_distributions', to='primary_docs.Car', verbose_name='Автомобиль')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_distributions', to='primary_docs.OutfitEvent', verbose_name='Вид работ')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_distributions', to='primary_docs.Station', verbose_name='Участок')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_distributions', to='primary_docs.Worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Распределение ГСМ',
                'verbose_name_plural': 'Распределения ГСМ',
            },
        ),
        migrations.AddField(
            model_name='waybill',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='primary_docs.OutfitEvent', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='fuel_distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits', to='primary_docs.FuelDistribution', verbose_name='Распределение ГСМ'),
        ),
        migrations.AddField(
            model_name='tractorregform',
            name='fuel_distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regforms', to='primary_docs.FuelDistribution', verbose_name='Распределение ГСМ'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='fuel_distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='primary_docs.FuelDistribution', verbose_name='Распределение ГСМ'),
        ),
    ]
