# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-10 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0042_auto_20190109_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueldistribution',
            name='event',
        ),
    ]
