# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-14 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primary_docs', '0043_remove_fueldistribution_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActSpisanya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('order', models.CharField(max_length=50, null=True, verbose_name='Распоряжение')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_spisanya', to=settings.AUTH_USER_MODEL, verbose_name='Составитель')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='act_spisanya', to='primary_docs.Organization', verbose_name='Организация')),
                ('outfit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='act_spisanya', to='primary_docs.Outfit', verbose_name='Наряд-акт')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='act_spisanya', to='primary_docs.Station', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Акт списания материальных запасов',
                'verbose_name_plural': 'Акты списания материальных запасов',
            },
        ),
    ]
