# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-15 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0044_actspisanya'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_head', to='primary_docs.Worker', verbose_name='Руководитель'),
        ),
    ]
