# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-17 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_docs', '0045_organization_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outfits', to='primary_docs.Organization', verbose_name='Организация'),
        ),
    ]
